# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{go_picasa_go}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pedro Dias"]
  s.date = %q{2010-10-10}
  s.description = %q{Go Picasa go is intended as library written in ruby to manipulate Picasa albums and photos in a easy way. The idea is to provide behaviors to ordinary objects so they can create, retrieve, update and delete albums and photos in a more object oritented way, lefting behind all the HTTP talk that was necessary previouly to interect with this service provided by Google.}
  s.email = %q{pedro.capaca@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "go_picasa_go.gemspec",
     "init.rb",
     "lib/go_picasa_go.rb",
     "lib/patchs/object.rb",
     "lib/patchs/ssl.rb",
     "lib/picasa/album.rb",
     "lib/picasa/authentication.rb",
     "lib/picasa/http/album.rb",
     "lib/picasa/http/authentication.rb",
     "lib/picasa/http/photo.rb",
     "lib/picasa/photo.rb",
     "lib/picasa/user.rb",
     "lib/picasa/util.rb",
     "script.rb",
     "spec/album_spec.rb",
     "spec/authentication_spec.rb",
     "spec/fixture/photo.jpg",
     "spec/fixture/photo2.jpg",
     "spec/http/album_spec.rb",
     "spec/http/authentication_spec.rb",
     "spec/http/photo_spec.rb",
     "spec/http_response_helper.rb",
     "spec/mock_helper.rb",
     "spec/photo_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_suite.rb",
     "spec/user_spec.rb"
  ]
  s.homepage = %q{http://github.com/capaca/go-picasa-go}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{API to easly manipulate picasa albums and photos}
  s.test_files = [
    "spec/test_suite.rb",
     "spec/user_spec.rb",
     "spec/authentication_spec.rb",
     "spec/album_spec.rb",
     "spec/http_response_helper.rb",
     "spec/spec_helper.rb",
     "spec/http/authentication_spec.rb",
     "spec/http/album_spec.rb",
     "spec/http/photo_spec.rb",
     "spec/mock_helper.rb",
     "spec/photo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

