# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{go_picasa_go}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pedro Dias"]
  s.date = %q{2010-10-21}
  s.default_executable = %q{go-picasa-go}
  s.description = %q{Go Picasa go is intended as library written in ruby to manipulate Picasa albums and photos in a easy way. The idea is to provide behaviors to ordinary objects so they can create, retrieve, update and delete albums and photos in a more object oritented way, lefting behind all the HTTP talk that was necessary previouly to interect with this service provided by Google.}
  s.email = %q{pedro.capaca@gmail.com}
  s.executables = ["go-picasa-go"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/go-picasa-go",
     "go_picasa_go.gemspec",
     "init.rb",
     "lib/go_picasa_go.rb",
     "lib/patchs/object.rb",
     "lib/patchs/ssl.rb",
     "lib/picasa/album.rb",
     "lib/picasa/authentication.rb",
     "lib/picasa/default_album.rb",
     "lib/picasa/default_photo.rb",
     "lib/picasa/default_user.rb",
     "lib/picasa/http/album.rb",
     "lib/picasa/http/authentication.rb",
     "lib/picasa/http/photo.rb",
     "lib/picasa/photo.rb",
     "lib/picasa/template/album.xml.erb",
     "lib/picasa/template/photo.erb",
     "lib/picasa/user.rb",
     "lib/picasa/util.rb",
     "script.rb",
     "spec/album_spec.rb",
     "spec/authentication_spec.rb",
     "spec/default_classes_spec.rb",
     "spec/fixture/photo.jpg",
     "spec/fixture/photo2.jpg",
     "spec/http/album_spec.rb",
     "spec/http/authentication_spec.rb",
     "spec/http/photo_spec.rb",
     "spec/http_response_helper.rb",
     "spec/mock_helper.rb",
     "spec/photo_spec.rb",
     "spec/spec_helper.rb",
     "spec/suites/all.rb",
     "spec/suites/all_mocked.rb",
     "spec/user_spec.rb"
  ]
  s.homepage = %q{http://github.com/capaca/go-picasa-go}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{API to easly manipulate picasa albums and photos}
  s.test_files = [
    "spec/mock_helper.rb",
     "spec/default_classes_spec.rb",
     "spec/user_spec.rb",
     "spec/http_response_helper.rb",
     "spec/http/photo_spec.rb",
     "spec/http/authentication_spec.rb",
     "spec/http/album_spec.rb",
     "spec/photo_spec.rb",
     "spec/authentication_spec.rb",
     "spec/spec_helper.rb",
     "spec/album_spec.rb",
     "spec/suites/all_mocked.rb",
     "spec/suites/all.rb",
     "examples/rails-example/db/seeds.rb",
     "examples/rails-example/config/environments/production.rb",
     "examples/rails-example/config/environments/test.rb",
     "examples/rails-example/config/environments/development.rb",
     "examples/rails-example/config/routes.rb",
     "examples/rails-example/config/boot.rb",
     "examples/rails-example/config/initializers/session_store.rb",
     "examples/rails-example/config/initializers/new_rails_defaults.rb",
     "examples/rails-example/config/initializers/backtrace_silencers.rb",
     "examples/rails-example/config/initializers/mime_types.rb",
     "examples/rails-example/config/initializers/inflections.rb",
     "examples/rails-example/config/environment.rb",
     "examples/rails-example/test/performance/browsing_test.rb",
     "examples/rails-example/test/test_helper.rb",
     "examples/rails-example/test/functional/albums_controller_test.rb",
     "examples/rails-example/test/unit/helpers/albums_helper_test.rb",
     "examples/rails-example/app/controllers/application_controller.rb",
     "examples/rails-example/app/controllers/albums_controller.rb",
     "examples/rails-example/app/helpers/albums_helper.rb",
     "examples/rails-example/app/helpers/application_helper.rb",
     "examples/rails-example/app/models/user.rb",
     "examples/rails-example/app/models/album.rb",
     "examples/rails-example/app/models/photo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

