require 'net/https'
require 'erb'
require 'tmpdir'
require 'rubygems'
require 'nokogiri'
require 'patchs/ssl'
require 'picasa/http/authentication'
require 'picasa/http/album'
require 'picasa/http/photo'
require 'picasa/http/album_client'
require 'picasa/http/photo_client'
require 'picasa/http/auth_sub'
require 'picasa/http/auth_sub_photo'
require 'picasa/http/auth_sub_album'
require 'picasa/http/client_login'
require 'picasa/util'
require 'picasa/missing'
require 'picasa/authentication'
require 'picasa/user'
require 'picasa/album'
require 'picasa/photo'
require 'picasa/exceptions'
require 'patchs/object'
require 'singleton'
require 'generators/user_class_generator'
require 'picasa/session'
require 'picasa/auth_sub_session'

include Picasa::Util

require 'picasa/default_user'
require 'picasa/default_photo'
require 'picasa/default_album'


