require 'net/https'
require 'erb'
require 'rubygems'
require 'nokogiri'
require 'patchs/ssl'
require 'patchs/object'
require 'http/authentication'
require 'http/album'
require 'http/photo'
require 'util'
require 'authentication'
require 'user'
require 'album'
require 'photo'

