# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{go-picasa-go}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pedro Dias"]
  s.date = %q{2010-10-09}
  s.description = %q{Go Picasa go encapsulates the HTTP operations provided by Google to manipulate albums and photos.}
  s.email = %q{pedro.capaca@gmail.com}
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "go-picasa-go.gemspec",
     "lib/album.rb",
     "lib/authentication.rb",
     "lib/go_picasa_go.rb",
     "lib/http/album.rb",
     "lib/http/authentication.rb",
     "lib/http/photo.rb",
     "lib/photo.rb",
     "lib/picasa.rb",
     "lib/template/album.xml.erb",
     "lib/template/photo.erb",
     "lib/user.rb",
     "lib/util.rb",
     "pkg/go-picasa-go-0.0.1.gem",
     "script.rb",
     "spec/album_spec.rb",
     "spec/authentication_spec.rb",
     "spec/fixture/photo.jpg",
     "spec/fixture/photo2.jpg",
     "spec/http/album_spec.rb",
     "spec/http/authentication_spec.rb",
     "spec/http/photo_spec.rb",
     "spec/http_response_helper.rb",
     "spec/mock_helper.rb",
     "spec/photo_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_suite.rb",
     "spec/user_spec.rb"
  ]
  s.homepage = %q{http://github.com/capaca/go-picasa-go}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{API to easly manipulate picasa albums and photos}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

